#!/usr/bin/env python3
"""
add_ai_summary.py - Adds the `ai_summary` field to every strategy.

The AI Summary is a Claude-authored analysis displayed above the "How It Works"
section on each strategy page. For each strategy, Claude reviews the structure,
assets, signals/logic, performance metrics, and backtest period, then explains
why someone would follow it, the purpose behind its logic, and any noteworthy
characteristics (short backtests, high drawdown, period-dependent returns).

This script writes the `ai_summary` (an array of paragraph strings) into both
`data/strategies.json` and `data/strategies.js`, inserting it immediately before
`how_it_works` so the data file reads in display order. Safe to re-run: it
overwrites any existing `ai_summary` and leaves all other fields untouched.

Usage:
    python scripts/add_ai_summary.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
JSON_PATH = ROOT / "data" / "strategies.json"
JS_PATH = ROOT / "data" / "strategies.js"

JS_HEADER = (
    "// Strategies data - loaded as a script tag so the site works with file:// protocol.\n"
    "// To update metrics: run scripts/update_metrics.py\n"
    "window.STRATEGIES_DATA = "
)

# slug -> list of paragraph strings
AI_SUMMARIES = {
    "zoops-frontrunner": [
        "Stripped to its essence, zoop's Frontrunner is a bet that short-term RSI extremes are reliable turning points, and it takes that bet in both directions with leverage. Most of the time it is simply long SPY, so its baseline is the market itself. The strategy only earns or loses its edge in the tails: at the bottom it swaps into a 3x fund to catch the sharpest available bounce, and at the top it swaps into long volatility to front-run the pullback its name refers to. What makes it unusual among the leveraged strategies here is how rarely it is actually leveraged. Every branch is all-or-nothing and the default state is unlevered, which is why its volatility sits far below what a permanent 3x holding would produce. It is best understood as an SPY position with two rented options attached, one on a violent bounce and one on a violent top, rather than as a leveraged strategy that occasionally steps aside.",
        "The backtested numbers are strong: 77% annualized with a 1.68 Sharpe and a 2.68 Calmar against a 29% max drawdown and 38% volatility, over roughly 8.6 years. Four cautions matter, and the first outweighs the rest. The symphony's logic was last edited on 1 September 2026, so it has no out-of-sample record whatsoever; every figure here describes the same window the rules were selected against. Second, the backtest cannot begin before January 2018 because VXX is the youngest instrument in its universe, so the record misses 2008 and the 2015 to 2016 selloff outright. Third, the thresholds are precise in a way that invites overfitting: 23, 28, 28 and 79 are tuned numbers, and a twelve-name overbought basket carries a great many degrees of freedom for its size. Fourth, the compounded return leans on a small number of days, so it depends on a handful of switches having been timed correctly. The simplicity is a genuine virtue, the whole tree can be audited in a minute, but simplicity is not the same as robustness, and a freshly-edited strategy has earned no evidence yet.",
    ],
    "rains-unified-best-signals": [
        "Stripped to its essence, Rain's Unified Best Signals is a diversified, permanently-hedged bet on leveraged US tech that refuses to lean on any one signal. It stacks a large number of independent community strategies, TQQQ For The Long Term, The Holy Grail, KMLM Fund Surfing, Garen Phillips' dip-buyer, and a Safe Sectors bond rotation, and equal-weights them so that trend, momentum, mean-reversion, and managed-futures signals all vote at once. A VIX 'frontrunner' layer sits in front, stepping into UVXY or VIXY the moment several indices reach overbought RSI extremes, and a defensive 'Safe Sectors or Bonds' rotation absorbs capital whenever the leveraged sleeves stand down. The idea is that blending many proven signals smooths the ride and keeps the drawdown far shallower than any single leveraged strategy would.",
        "The backtested numbers are extraordinary and unusually well-balanced: 461% annualized with a 3.26 Sharpe and a 21.05 Calmar, against a 22% max drawdown that is remarkably shallow for 58% volatility and heavy 3x exposure. Three cautions matter. First, the backtest is short, roughly 5.7 years, and only went out-of-sample in November 2025, so almost the entire record is an in-sample fit spanning the 2022 bear and the 2023 to 2025 AI bull, a stretch unusually kind to hedged dip-buyers. Second, the sheer complexity, dozens of stacked, individually-tuned thresholds, carries real overfitting risk: an ensemble this large can fit its own window more tightly than it generalizes. Third, it is still a leveraged system, so the shallow historical drawdown should be read as a property of a favourable, mostly in-sample window rather than a guarantee. Best understood as an ambitious attempt to diversify signal risk within leveraged tech, whose spectacular ratios deserve heavier discounting than a long, out-of-sample record would.",
    ],
    "zoops-2026-frontrunner": [
        "Structurally, the Frontrunner is a cash-first dip-buyer: it parks in T-bills (BIL) by default and only deploys into 3x leveraged ETFs (SOXL, TQQQ, or UPRO) when a fast RSI(10) reading crosses tight oversold thresholds, with semiconductors checked first. A second branch uses XLY and UVXY RSI to rotate into volatility (VXX) or a short (SPXU) when markets overheat. The purpose is to spend most of its time earning risk-free interest and act only at genuine short-term extremes, making each entry deliberate rather than continuous. It is also the 50% base component shared by every other zoop symphony, so understanding it explains half of this library.",
        "Over a roughly 8-year backtest it posts a 91% annualized return with a 22% max drawdown, a notably lower drawdown than the other leveraged zoop strategies precisely because its time-in-market is limited. Its 1.78 Sharpe and 4.23 Calmar reflect that favorable risk-adjusted trade-off. The main caveat is that buying into oversold conditions means individual entries can keep falling before they recover, so the smooth equity curve masks sharp single-trade risk. It best suits an investor who wants systematic dip-buying exposure rather than a constant leveraged allocation.",
    ],
    "zoops-holy-grail-2026": [
        "This is a full-cycle, multi-signal strategy that layers RSI, the 200-day moving average, and volatility filters on top of the shared Frontrunner dip-buy base. The moving-average gate defines the broad regime, RSI handles overbought and oversold timing, and the volatility check routes into hedges when conditions turn turbulent. The intent is to capture leveraged upside in bull trends while using multiple independent confirmations to step aside before the worst of a drawdown, the 'holy grail' being strong compounding that still survives full market cycles.",
        "Across a long 14-year backtest it returns 113% annualized, the result of combining many signals over many regimes. The trade-off is a deep 45% max drawdown and high 54% volatility, marking it as an aggressive leveraged strategy, and the 1.65 Sharpe and 2.53 Calmar are solid but not exceptional for the risk taken. The long backtest is a real strength here: it has been tested through 2018, 2020, and 2022 stress periods rather than a single favorable stretch. It suits investors comfortable holding through large paper losses in pursuit of high long-run growth.",
    ],
    "zoops-tqqq-long-term-2026": [
        "The logic is a long-term TQQQ (3x Nasdaq 100) holding wrapped in systematic safety exits. Rather than buy-and-hold, it uses the 200-day moving average and RSI/volatility checks to step out of leveraged tech before major breakdowns, then re-enter when conditions stabilize, all on top of the shared Frontrunner dip-buy base. It is built for the investor who believes in Nasdaq 100 growth over the long run but cannot stomach the catastrophic, decay-amplified losses that come from holding a 3x ETF unhedged through a bear market.",
        "Over roughly 14 years it compounds at 111% annualized, but the headline risk is a 46% max drawdown and 55% volatility; the safety exits soften the worst leveraged-tech crashes without eliminating them. Its 1.63 Sharpe and 2.40 Calmar are typical for this aggressive cohort. The value proposition is less about beating the other zoop variants and more about converting an un-survivable 3x buy-and-hold into something an investor can actually hold through a cycle.",
    ],
    "zoops-excellent-adventure-2026": [
        "This variant is the most aggressive of the 'rotation' zoops: it dynamically moves across high-momentum leveraged instruments using RSI, 200-day MA, and volatility signals, aiming to always be positioned in whatever is compounding fastest while the Frontrunner base handles dip-buying. The purpose is maximal participation in leveraged momentum, chasing the strongest trend rather than committing to a single ticker like TQQQ or UPRO.",
        "It delivers 122% annualized over roughly 14 years with the best Sharpe (1.82) of the core leveraged zoop variants, meaning its return per unit of risk is comparatively efficient despite a 46% max drawdown and 51% volatility. The long backtest spanning multiple cycles lends credibility. Still, the 'always in the hottest asset' design makes it whipsaw-prone in choppy, trendless markets, and the deep drawdown places it firmly in aggressive territory.",
    ],
    "zoops-sometimes-tqqq-2026": [
        "As the name suggests, this strategy holds TQQQ only when multiple independent signals (RSI, the 200-day MA regime, and volatility filters) simultaneously confirm a favorable entry; otherwise it sits in the defensive Frontrunner base or cash. It is a precision-timing approach: the logic is deliberately selective, trading time-in-market for entry quality, on the thesis that avoiding leveraged exposure during unconfirmed conditions is worth more than capturing every up day.",
        "That selectivity pays off statistically: it records the strongest risk-adjusted profile in the library, a 2.47 Sharpe and 5.22 Calmar, alongside a 182% annualized return and the highest backtested cumulative return here, all over a robust 14-year window. Its 35% max drawdown is meaningfully shallower than the always-in TQQQ variants. The standout characteristic is this efficiency: by being TQQQ 'sometimes' rather than always, it captures much of the upside with materially less of the pain, making it one of the more compelling profiles for risk-aware leveraged investors.",
    ],
    "zoops-safety-checks-2026": [
        "This strategy front-loads multiple pre-position 'safety checks' (RSI extremes, 200-day MA regime, and volatility conditions) that must clear before it commits to a leveraged ETF, otherwise defaulting to the conservative Frontrunner base. The design philosophy is drawdown reduction first: each check is a veto gate intended to keep the strategy out of leveraged positions during the conditions that historically precede large losses, while still compounding strongly over the long run.",
        "Over roughly 14 years it returns 102% annualized with a 44% max drawdown and 51% volatility; the 1.63 Sharpe and 2.36 Calmar are mid-pack for the cohort. In practice the safety checks moderate rather than eliminate leveraged drawdowns, and the deep max drawdown shows that no set of pre-entry filters fully neutralizes 3x ETF risk in a severe selloff. It suits an investor who wants a more cautious, gated version of leveraged tech exposure but understands the residual downside remains substantial.",
    ],
    "zoops-manhattan-project-2026": [
        "The Manhattan Project is the most signal-dense zoop variant, integrating many independent market indicators (RSI, moving averages, momentum, and volatility tiers) to assemble what it treats as an optimal leveraged position at each rebalance, layered over the Frontrunner base. It approaches market timing as a quasi-scientific exercise: more inputs, more conditional branches, and a composite read of regime intended to position aggressively only when the weight of evidence agrees.",
        "The complexity translates into strong numbers: 154% annualized over roughly 14 years with a 2.10 Sharpe and 4.43 Calmar, and a 35% max drawdown that is shallower than most always-on leveraged peers. The long, multi-cycle backtest is a strength. The flip side of heavy signal-stacking is overfitting risk, since many tuned thresholds can fit the historical period more tightly than they generalize, so the excellent backtest should be read with the understanding that complex strategies carry more parameter risk out-of-sample.",
    ],
    "zoops-kmlm-switcher-2026": [
        "This is a regime-switching strategy that rotates between KMLM, a managed-futures, trend-following ETF that tends to do well when equities struggle, and leveraged equity ETFs, using RSI and volatility signals plus the Frontrunner base. The purpose is to be positioned for gains in two opposite environments: riding leveraged equities when markets rally, and pivoting to managed-futures trend exposure when they do not, creating a more all-weather return stream than a pure equity-leverage approach.",
        "It posts the headline-grabbing numbers of this library: 280% annualized, a 2.63 Sharpe, and a remarkable 9.52 Calmar with only a 30% max drawdown. The critical caveat is the backtest length. At roughly 5 years (1,377 trading days) it is far shorter than the 14-year zoop variants, and managed-futures diversification looked especially good across the specific 2021 to 2022 period when KMLM rallied as stocks fell. Those extraordinary ratios are therefore more period-dependent and should be discounted relative to the longer-tested strategies.",
    ],
    "zoops-upro-ftlt-2026": [
        "This is the S&P 500 counterpart to the TQQQ long-term strategy: it holds UPRO (3x S&P 500) for the long run with the same systematic safety-exit framework of 200-day MA regime gating, RSI/volatility checks, and the Frontrunner dip-buy base. Because the S&P 500 is broader and less concentrated than the Nasdaq 100, the strategy is designed to deliver similar leveraged trend-following behavior with a somewhat smoother ride than its QQQ-based sibling.",
        "Over roughly 14 years it returns 94% annualized with a 33% max drawdown and 47% volatility, both lower than the TQQQ version, confirming the broader-index, lower-beta intent, while the 1.64 Sharpe and 2.81 Calmar land mid-pack. It is the natural pick for an investor who wants the long-term-leverage-with-safety-exits concept but prefers S&P 500 breadth over Nasdaq 100 concentration, accepting modestly lower returns for modestly lower volatility.",
    ],
    "zoops-leveraged-tqqq-symphony-2026": [
        "This TQQQ strategy 'orchestrates' multiple timing signals (RSI, 200-day MA, momentum, and volatility tiers) and acts only when they align, much like instruments playing in harmony, on top of the shared Frontrunner base. Conceptually it is close to the other TQQQ-long-term variants but frames its edge as signal coordination: each indicator must agree before leveraged exposure is taken, the goal being to avoid acting on any single signal in isolation.",
        "Across roughly 14 years it compounds at 109% annualized, but it carries the deepest max drawdown of the core TQQQ variants at 48%, with 53% volatility and a 1.64 Sharpe and 2.28 Calmar. The long backtest is reassuring, but the relatively weak Calmar shows that requiring signal 'harmony' did not, historically, buy meaningfully better drawdown protection than simpler approaches, making it a solid but not standout member of the TQQQ family.",
    ],
    "zoops-tqqq-200d-ma-3x-2026": [
        "This is the simplest, most transparent strategy in the library: hold TQQQ when QQQ is above its 200-day moving average, otherwise move to cash, with the Frontrunner base handling opportunistic dip-buys. The single 200-day MA gate is one of the most studied and durable trend filters in systematic investing, and the appeal here is exactly that legibility. Anyone can understand, audit, and trust the rule, with no opaque stack of tuned thresholds.",
        "Over roughly 14 years it returns 109% annualized with a 39% max drawdown, 53% volatility, and a 1.65 Sharpe and 2.80 Calmar, performance fully competitive with far more complex variants. That is the noteworthy point: a one-rule strategy matches the multi-signal symphonies, a strong argument that most of the value comes from the trend gate itself rather than the added complexity. Its low overfitting risk and interpretability make it an excellent baseline for understanding leveraged trend-following.",
    ],
    "zoops-soxl-growth-2026": [
        "This is the most aggressive zoop symphony, using SOXL (3x Semiconductors) as its core growth engine, governed by RSI, momentum, and volatility signals plus the Frontrunner base. Semiconductors are among the highest-beta corners of the market, and 3x leverage on top compounds that volatility. The strategy deliberately accepts extreme swings in exchange for the explosive upside that semiconductor leadership can deliver during a tech bull run.",
        "The numbers make the trade-off explicit: 164% annualized over roughly 14 years, but a brutal 66% max drawdown and 69% volatility, the highest-risk profile of the zoop set, which is why it carries max-drawdown and standard-deviation tags. Its 1.75 Sharpe and 2.50 Calmar are respectable only because the returns are so large. This is a strategy for investors with the highest risk tolerance and a long horizon who can psychologically and financially survive losing roughly two-thirds of peak value.",
    ],
    "s90-half-low-catch": [
        "This strategy is an equal-weighted 50/50 blend of two components that run side by side. The 'low catchers' half is a waterfall of extreme oversold triggers across 3x ETFs (semiconductors, biotech, China, financials, small caps, global markets) that stays dormant until an asset reaches a genuine washout, then buys the snapback at RSI levels far below conventional oversold thresholds. The other half is a complete 's90 50/40 maxDD' bull/bear regime strategy that is always invested, rotating between leveraged equity baskets (SOXL, TQQQ, TECL, UPRO), volatility hedges (UVXY, VIXY), and a small BIL/GLD/TLT ballast sleeve. So the portfolio is never wholly idle: one half hunts capitulation while the other actively trades the trend.",
        "Its backtested figures are spectacular (470% annualized, a 2.58 Sharpe, and an 11.46 Calmar with a 41% max drawdown) but they demand heavy skepticism. The backtest is just 2.4 years (605 trading days), by far the shortest in the library, and a strategy weighted half toward deep-dip-buying will look extraordinary in any window that happens to contain sharp V-shaped recoveries. These returns are almost certainly not repeatable out-of-sample; the strategy is best viewed as an illustration of the mean-reversion-plus-regime concept rather than a realistic expectation, and the short, period-specific backtest is its single most important caveat.",
    ],
    "holy-grail": [
        "The original Holy Grail is a TQQQ-centric trend-follower: it stays long leveraged tech while TQQQ holds above its 200-day moving average, hedges into UVXY when the market is overbought, and rotates into dip-buying or outright short positions once TQQQ breaks below the 200-day line. The logic is a clean three-state machine of bull (long leverage), froth (volatility hedge), and bear (dip-buy or short), designed to participate fully in uptrends while having explicit, pre-defined responses to overheating and to regime breakdown.",
        "Over a long 15-year backtest it returns 150% annualized with a 1.77 Sharpe and 3.17 Calmar, while the 47% max drawdown and 63% volatility mark it as aggressive. The lengthy test window through multiple bear markets is a meaningful strength, and the explicit short and hedge branches mean it is built to profit from, not merely survive, downturns. It suits investors who want active bull-and-bear leveraged tech exposure governed by a transparent moving-average regime rule.",
    ],
    "tqqq-long-term": [
        "This is a TQQQ buy-and-hold core wrapped in a comprehensive risk-management overlay. SPY's 200-day moving average sets the bull/bear regime; in bull markets it runs TQQQ with dual overbought guards on TQQQ and SPXL plus RSI-triggered dip-buying into TECL and UPRO, and in bear markets it filters between SQQQ and the TLT bond hedge by RSI. The purpose is to hold leveraged Nasdaq exposure for the long term while having layered, rules-based defenses against the drawdowns that destroy unhedged 3x positions.",
        "Across roughly 15 years it compounds at 160% annualized with a strong 1.83 Sharpe and 2.99 Calmar. The headline risk is a 54% max drawdown and 63% volatility, among the deeper drawdowns here, a reminder that even a well-engineered overlay cannot fully tame 3x exposure. The long, multi-cycle backtest and the explicit bond-hedge bear branch are its strengths; it fits a long-horizon investor who wants leveraged tech with genuine defensive machinery rather than naked buy-and-hold.",
    ],
    "wooden-arkk": [
        "This is a bi-directional mean-reversion strategy built around ARKK's leveraged siblings. It reads the market regime by comparing IEI (treasuries) and SPHB (high-beta) RSI, then buys the single worst recent performer from either a long leveraged pool (when conditions are risk-off and a bounce is likely) or an inverse-ETF pool (when conditions are risk-on and a pullback is likely). The 'buy the biggest loser' mechanic is pure short-horizon mean reversion, with the IEI-versus-SPHB read deciding which direction to fade.",
        "It shows 229% annualized over a roughly 4.3-year (about 1,080-day) backtest with a 2.18 Sharpe and 5.14 Calmar against a 45% max drawdown. The strong ratios are attractive, but the short record begins around mid-2022 and is skewed toward the high-volatility 2022 to 2025 environment in which fade-the-extreme tactics thrive; the same approach can bleed in calm, persistently trending markets where the worst performer keeps losing. Treat the impressive metrics as period-specific and the strategy as a tactical, volatility-dependent mean-reversion play.",
    ],
    "super-semiconductors": [
        "A semiconductor-sector specialist by Dereck Nielsen, this strategy selects the top 3 performers from a 19-company chip universe during MACD-bullish bull markets, switches to tactical dip-buying and partial bond hedges when MACD turns bearish, and actively shorts semiconductors via SOXS or SSG in confirmed bear conditions. It combines stock-level momentum selection (own the strongest chips) with a sector-level MACD regime switch, so it concentrates in winners during uptrends and flips defensive or short when the sector rolls over.",
        "Over a long 14-year backtest it returns 99% annualized with a 1.66 Sharpe, 2.32 Calmar, and a 43% max drawdown, a relatively contained drawdown for a single-sector strategy, helped by the bond hedges and short branches. The multi-cycle test window and the genuine bear-market shorting logic are strengths. Its main characteristic is concentration: by living entirely in semiconductors it is fully exposed to chip-cycle booms and busts, rewarding investors who specifically want active, regime-aware exposure to that sector.",
    ],
    "four-horsemen": [
        "This is a multi-component, equal-weight strategy that runs several market-cycle systems in parallel: a SPY 200-day trend engine with 5-ETF momentum selection, a shorter-term TQQQ 20-day component, and a secondary SPY regime component, all sharing dual UVXY overbought guards and a cascading bear-market protocol that includes dip-buying, deep-bear routing, and a QQQ cumulative-return detector. Equal-weighting independent sub-strategies is a diversification technique: each 'horseman' captures a different timeframe or signal, and blending them smooths the combined equity curve.",
        "Across roughly 14 years it returns 162% annualized with a strong 2.14 Sharpe and 3.58 Calmar against a 45% max drawdown and 51% volatility. The combination of a long backtest, parallel-system diversification, and layered bear protocols gives it one of the more robust risk-adjusted profiles among the original (non-zoop) strategies. The cost is complexity, since many interacting components are harder to audit and carry more parameter risk, but the multi-system design is a deliberate hedge against any single signal failing.",
    ],
    "soxx-group": [
        "A semiconductor specialist by Garen/DN, this strategy uses UVXY's 30-day RSI to detect high-volatility regimes, then trades SOXL or SOXS based on the size of single-day moves in SMH, applying a tiered multi-timeframe RSI cascade it calls the '30-20-10 Double Pop' to catch mean reversion after extreme semiconductor swings. The design is explicitly volatility-gated mean reversion: it only engages when chips are moving violently, and uses nested RSI timeframes to time the snapback in either direction.",
        "Over a long 14-year backtest it returns 110% annualized, but the risk is severe: a 69% max drawdown, 67% volatility, and the weakest risk-adjusted figures of this group (1.44 Sharpe, 1.60 Calmar). The noteworthy characteristic is that the strategy takes very large losses relative to its returns, since fading extreme single-sector moves works until a move keeps going, and 3x chip ETFs punish a wrong-way bet harshly. It is a high-conviction, high-pain semiconductor tool, not a balanced allocation.",
    ],
    "soxl-growth-rl": [
        "This is a machine-learning-optimized SOXL strategy (the 'RL' stands for Reinforcement Learning) that uses standard deviation of returns alongside RSI and drawdown thresholds to navigate between long semiconductor exposure, inverse ETFs, and diversified leveraged baskets. The hyper-precise, oddly specific numeric thresholds betray its algorithmic origin: rather than round human-chosen levels, the boundaries were fitted by an optimization process searching for the best historical configuration.",
        "It returns 135% annualized over a long 15-year backtest but carries the deepest drawdown in the entire library at 88%, with extreme 86% volatility and weak 1.43 Sharpe and 1.54 Calmar ratios. Two cautions dominate. First, an 88% drawdown means the strategy lost nearly nine-tenths of peak value at its worst, which few investors could hold through. Second, RL and optimized strategies are especially prone to overfitting, because thresholds tuned to maximize a past backtest often degrade out-of-sample. The long test window helps, but the algorithmic curve-fitting risk and catastrophic drawdown are the headline concerns.",
    ],
    "nancy-pelosi-chips": [
        "Named after the well-publicized chip-stock trading, this is a semiconductor mean-reversion strategy that uses 5-day SOXX cumulative returns to detect weekly momentum extremes, then trades SOXL or SOXS at the reversal point, while applying individual RSI checks on NVDA and AMD to catch extreme overbought and oversold conditions in the two bellwether names. The thesis is short-horizon reversion in chips: fade weekly extremes and lean on the most influential individual stocks to confirm the turn.",
        "This is the weakest risk-adjusted profile in the library, and its metrics should be read as a cautionary example: 75% annualized over roughly 14 years, but an 86% max drawdown, the second deepest here behind SOXL Growth (Original), with a 1.11 Sharpe and a Calmar of just 0.87, meaning the annualized return is actually smaller than the maximum loss endured to earn it. Fading single-sector momentum without a strong regime gate exposes it to ruinous trends where the 'extreme' keeps extending. The long backtest only underscores that the poor ratios are structural, not a small-sample artifact; this strategy illustrates how high single-sector leverage can produce large returns and unacceptable risk simultaneously.",
    ],
    "top-cap-ma-rsi": [
        "This is a clean three-branch strategy gated by SPY's extreme short-term RSI. When SPY is extremely overbought it rotates into a UVXY volatility hedge; when extremely oversold it attacks with leveraged ETFs; and in the normal middle state it runs momentum selection from a curated mega-cap basket spanning value, growth, and crypto-proxy names. The structure is intuitive (hedge the froth, buy the panic, and otherwise own the strongest large caps) which keeps it far more legible than the deeply nested semiconductor strategies.",
        "Over an 11-year backtest it returns 127% annualized with a 1.60 Sharpe, 2.20 Calmar, and a 58% max drawdown. The notable risk is that drawdown: despite using only RSI and momentum, the leveraged-attack branch and high-beta mega-cap basket still produce deep losses in severe selloffs. Its appeal is simplicity and breadth, a transparent rule set over a diversified large-cap universe, for an investor who wants clear logic and accepts aggressive drawdowns.",
    ],
    "mean-reversion-py": [
        "This is a deliberately minimalist SPY trend-follower with a TQQQ core and a UVXY overbought hedge, originally written to cross-validate a Python backtesting implementation. SPY's moving average is the only regime gate and TQQQ's 10-day RSI is the only secondary signal, producing just four simple branches that choose between TQQQ, UVXY, and SPY. Its value is pedagogical: it is the clearest possible illustration of a moving-average regime gate plus a single RSI hedge, with nothing else to obscure the mechanism.",
        "Over roughly 15 years it returns about 79% annualized, but the bare-bones design shows in the risk: an 82% max drawdown, 65% volatility, and a Calmar of 0.97, meaning the annualized return has not quite repaid the maximum drawdown, just under the breakeven line for risk-adjusted appeal. With only one hedge and no bond or short branch, it has little defense in a sustained bear market, which is why the drawdown is so deep. It is best understood as a reference implementation and a baseline for what minimal logic achieves, not as an optimized strategy to deploy as-is.",
    ],
    "spy-energy-chips": [
        "This is a two-component strategy. A 'VIXM Black Swan Catcher' holds mid-term VIX futures when volatility has been persistently elevated, providing a crisis hedge, while a multi-sector momentum rotator selects the single best performer from a diversified pool spanning semiconductor leaders, the broad market, energy, commodities, and clean energy. The combination pairs a tail-risk hedge with a breadth-seeking momentum engine, so the strategy aims to rotate into whatever sector is leading while holding insurance for volatility spikes.",
        "Over roughly 14 years it returns 71% annualized with a modest 1.17 Sharpe, a 1.09 Calmar, and a deep 65% max drawdown. The weak Calmar signals the core issue: the sector-momentum sleeve still suffers large drawdowns, and the VIXM hedge, which bleeds during calm markets, drags on returns more than it protects in this configuration. The diversified sector universe is genuinely broad, but the metrics suggest the hedge-plus-rotation balance is not well tuned; it is a moderate strategy whose risk outweighs its return relative to the leveraged peers here.",
    ],
    "simons-kmlm-switcher": [
        "Simon's KMLM Switcher is an aggressive three-layer RSI strategy. An 11-ticker overbought gate routes into UVXY whenever any tracked sector overheats; a sequential dip-buy cascade catches 3x ETF crashes at extreme oversold levels; and a KMLM momentum switch toggles between the two most oversold leveraged ETFs when tech leads, or defensive SQQQ/TLT when managed-futures momentum dominates. The layered design tries to do three jobs at once: hedge froth, buy capitulation, and pick the right regime between leveraged tech and managed-futures defense.",
        "Its backtested numbers are extraordinary (612% annualized, a 2.90 Sharpe, and a 19.10 Calmar against a 32% max drawdown) but the central caveat is the 4-year (1,098-day) backtest. Like the related KMLM Switcher, those ratios lean heavily on the 2021 to 2024 window, where managed-futures diversification and sharp dip-buys looked exceptional; such returns are not a reasonable forward expectation. The strategy is a sophisticated, all-weather-style design, but its short, period-specific test means the spectacular metrics should be discounted far more than those of the 14-year-tested strategies.",
    ],
    "bnd-vs-sphb": [
        "This strategy is built on a counterintuitive premise: when bonds (BND) are outperforming high-beta equities (SPHB) on a 10-day RSI basis, the strategy buys SOXL (3x semiconductors), the riskiest holding in this library. The logic inverts conventional risk-on thinking. BND momentum exceeding SPHB momentum signals a short-term risk-off sentiment extreme, which the strategy reads as a setup for a sharp reversal in speculative assets. The position is binary: fully in SOXL or fully in SHV (cash), with UVXY RSI tiers providing a separate volatility-based crash guard that can redirect to cash or SOXL depending on implied volatility conditions.",
        "Over approximately 14.7 years, the strategy posts 98.5% annualized returns with a 70% max drawdown, one of the deepest in this library. The backtest begins around May 2011 when SPHB launched, so it excludes both the 2008 financial crisis and the dot-com bust, two periods that would almost certainly produce larger drawdowns. The 100x+ returns are compelling but the 70% drawdown and the extreme SOXL concentration are the defining risk characteristics. This suits only investors who can accept losing most of their portfolio value mid-cycle while trusting that a relative RSI signal between bonds and high-beta stocks is a durable edge in semiconductors.",
    ],
    "dip-buying-tech": [
        "Dip Buying Tech is explicitly designed as a backtesting study and educational baseline, not a live portfolio strategy. The author built it to test whether a simple two-signal decision tree (a 200-day moving average trend gate plus a single oversold trigger) could survive the dot-com crash, which the 27.2-year backtest window starting April 1999 directly validates. The logic is three branches: hold SPY in bull markets, retreat to XLP consumer staples as the defensive base in bear markets, and dip-buy XLK technology when QQQ's 10-day RSI falls below 30. No leverage, no exotic tickers, nothing hidden.",
        "The 14.0% annualized return is modest but represents 27-plus years of live-through-it performance including two major crashes and a rate shock, all with a 26.3% max drawdown. Its value is conceptual: it demonstrates that even the simplest possible regime-plus-oversold structure can outperform passive SPY over the long run without leverage. The strategy is intentionally simple enough to explain in one sentence, making it the clearest possible baseline for understanding how more complex strategies in this library build on the same two-signal foundation.",
    ],
    "ob-os-staple-bonds": [
        "Ob Os Staple my Bonds V0.0 is the original baseline of a multi-version strategy series. The name decodes as Overbought/Oversold (Ob/Os) plus Staples (XLP) plus Bonds (VBF). The core logic is continuous relative-value rotation between two defensive assets: whichever of XLP (consumer staples) and VBF (Invesco Bond Fund) currently has the lower 10-day RSI receives the full allocation. This treats RSI as a relative beaten-down signal rather than an absolute threshold, rotating toward whichever defensive asset has been sold down more recently. The single offensive override fires when QQQ's RSI(10) falls to or below 30, rotating the entire portfolio to unleveraged QQQ for a mean-reversion dip-buy.",
        "The result is one of the most conservative profiles in this library: 17.3% annualized with a 19.6% max drawdown across 27.2 years including the dot-com crash, 2008 financial crisis, and 2022 rate shock. That combination of steady compounding and low drawdown reflects what a strategy looks like when its default state is always in something defensive. The V0.0 designation means this page covers only the 1999-start original; the author notes later versions (V0.1 through V0.3) use progressively shorter backtest windows, which typically improves reported metrics. This version is best understood as a long-run reference for defensive RSI rotation behavior across full market cycles.",
    ],
    "sometimes-tqqq": [
        "Sometimes TQQQ earns its name through a priority-first architecture: before any regime analysis, two unconditional safety checks run. If QQQ's 10-day RSI falls below 32, the strategy rotates immediately to TECL (3x tech sector) for an early dip-buy entry. If SPY's 10-day RSI falls below 30, it rotates to UPRO (3x S&P 500). These priority gates can fire regardless of the broader market regime. After the priority checks clear, the strategy routes through five sub-regimes: Choppy, Bull 1, Bull 2, Bear 1, and Bear 2, each deciding whether TQQQ exposure is warranted based on layered bond-versus-equity momentum signals, ultimately choosing between TQQQ, various leveraged alternatives, and defensive positions.",
        "Over approximately 14.7 years the strategy posts 320.3% annualized returns and a roughly 1.9 billion times cumulative return, among the highest backtest figures in this library, with a 45.5% max drawdown that is large in absolute terms but notably restrained relative to those headline numbers. The backtest starts around October 2011 when UVXY launched, excluding 2008 and the early stages of the 2010 flash crash. The 2.73 Sharpe and 7.03 Calmar are exceptional by any standard. The five-regime depth and the priority-gate architecture are the distinguishing design features: the strategy is not 'always TQQQ' or 'sometimes TQQQ based on one signal' but a carefully sequenced decision tree that treats TQQQ as the preferred outcome and routes away from it only under explicit disqualifying conditions.",
    ],
    "safe-sectors-or-bonds-original": [
        "Safe Sectors or Bonds is a pure defensive mean-reversion rotator, and this entry is its earliest 1999-start form, the seed that dozens of later Composer variants were forked from. The entire strategy is a single selection step: rank seven safe-haven funds by their 10-day RSI and hold the one that is most oversold, rebalanced daily. The pool mixes consumer staples (XLP) with income and municipal bond funds (BKT, VBF, NAN, MMU, PMM, EVN), so the strategy is always parked in something defensive and simply rotates toward whichever one the market has pushed down hardest. There is no leverage, no equity beta beyond staples, and no directional market call.",
        "Its numbers are modest by design and that is the point. Over its full history back to 1999, one of the longest backtests in this library at about 27 years, it compounds at about 20.8% annualized with a 41.0% max drawdown and the lowest volatility in the library at 16.1%, a 1.25 Sharpe and a 0.51 Calmar. The long window is its real strength: it has lived through the dot-com crash, 2008, 2020, and the 2022 rate shock rather than a single favorable stretch. The main caveat is that a basket of closed-end bond and municipal funds carries interest-rate and liquidity risk of its own, so the safe in the name means low equity beta, not the absence of drawdown.",
    ],
    "tqqq-or-not-original": [
        "TQQQ or Not is the seed of a large family of hold-3x-Nasdaq-but-only-when-conditions-allow strategies, and this is its original long-history build (source name 'TQQQ or not/Pop'). It is not a single default-plus-overrides rule but a small ensemble. One gate sits on top: a fast TQQQ RSI(10) above 79 is read as overbought and puts the whole book in UVXY. Below that gate the portfolio splits 50/50 into two sleeves that run at the same time. The first, 'BlackSwan MeanRev BondSignal', holds TQQQ in a normal market but steps to cash or a volatility pop when a six-day TQQQ crash beyond -12%, a QQQ or TMF drawdown, or a bond-versus-equity regime read says conditions are hostile. The second, 'Pop', is a set of RSI pop-bots across QQQ, SMH and SPY that go long leveraged funds when they are oversold, short them or buy UVXY when overbought, and hold cash otherwise, with a VIXM volatility read switching between a defensive tiered version and a more aggressive one.",
        "Over a long, multi-cycle backtest that begins around 2011 it compounds at about 109% annualized with a 29.7% max drawdown, a 2.05 Sharpe and a 3.69 Calmar. That drawdown is notably shallow for a strategy whose upside comes from 3x ETFs, which is the whole appeal of being in TQQQ sometimes rather than always: the overbought fade and the crash and pop gates take it out of the way of the worst leveraged declines. The trade-off is complexity. Many interacting RSI, cumulative-return and cross-asset thresholds fit the historical record more tightly than a single rule would, so some of the backtest polish should be read as parameter tuning rather than durable edge.",
    ],
    "beta-ballers-original": [
        "Strip away the complexity and Beta Ballers is mostly a buy-the-dip bet on leveraged funds: when a high-beta ETF sells off, it tends to buy the weakest recent performer expecting a bounce, and it wraps that core idea in layers of trend, interest-rate and volatility gates that pull it into inverse funds, bonds, commodities or volatility when conditions turn hostile. Despite the aggressive name it is more mean-reversion than momentum, with more of its selection steps picking the weakest recent performer than the strongest. That same density of branches and hand-tuned thresholds is the catch, making it powerful in the conditions it was shaped around but genuinely hard to reason about, and impossible to treat as a simple black box.",
        "The headline numbers are extraordinary, and they deserve equal skepticism. Since its December 2019 backtest start it shows about 721% annualized against a 78.3% max drawdown, a 2.69 Sharpe and a 9.21 Calmar. Three cautions dominate. The drawdown is brutal, meaning you would have had to sit through losing more than three-quarters of the account at the worst point; the backtest window opens right before the 2020 to 2021 leveraged bull run and leans heavily on it, while the trailing one-year return here is negative; and the sheer number of tuned branches makes overfitting a genuine risk rather than a footnote. Treat it as the seed concept behind a large family and a study in aggressive design, not a recommendation to deploy capital as it stands.",
    ],
}


def insert_ai_summary(strategy):
    """Return a new ordered dict with ai_summary inserted before how_it_works."""
    slug = strategy["slug"]
    if slug not in AI_SUMMARIES:
        print(f"  WARNING: no AI summary defined for slug '{slug}' - skipping")
        return strategy
    out = {}
    for key, value in strategy.items():
        if key == "ai_summary":
            continue  # drop any existing copy; we re-insert in the right spot
        if key == "how_it_works":
            out["ai_summary"] = AI_SUMMARIES[slug]
        out[key] = value
    # Fallback: strategy has no how_it_works - append at end
    if "ai_summary" not in out:
        out["ai_summary"] = AI_SUMMARIES[slug]
    return out


def main():
    with open(JSON_PATH, encoding="utf-8") as f:
        strategies = json.load(f)

    updated = [insert_ai_summary(s) for s in strategies]

    missing = [s["slug"] for s in updated if "ai_summary" not in s]
    if missing:
        raise SystemExit(f"ERROR: missing ai_summary for: {missing}")

    payload = json.dumps(updated, indent=2, ensure_ascii=False)

    with open(JSON_PATH, "w", encoding="utf-8") as f:
        f.write(payload + "\n")

    with open(JS_PATH, "w", encoding="utf-8") as f:
        f.write(JS_HEADER + payload + ";\n")

    print(f"Wrote ai_summary for {len(AI_SUMMARIES)} strategies to:")
    print(f"  {JSON_PATH}")
    print(f"  {JS_PATH}")


if __name__ == "__main__":
    main()
