#!/usr/bin/env python3
"""Regenerate data/guides.js from data/guides.json, and validate the links.

WHY THIS EXISTS AS A SCRIPT. Every .json data file on this site has a .js twin
assigning a window.* global, because the pages have to work when opened from the
file system where fetch() is blocked. The glossary's twin is maintained by hand
and its header says so. That is a standing invitation to drift: the failure mode
is a page that renders correctly over HTTP and silently serves stale content
from the file system, which is the worst shape of bug this repo keeps meeting.

Guides are generated instead. Edit data/guides.json and run this.

It also checks the cross-references, because a guide that links to a glossary
slug which does not exist renders a dead link with no error anywhere. That is
cheap to check here and invisible otherwise.

Python 3 standard library only, per the repo convention.
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'data', 'guides.json')
OUT = os.path.join(ROOT, 'data', 'guides.js')
GLOSSARY = os.path.join(ROOT, 'data', 'glossary.json')

CATEGORIES = {'testing', 'execution', 'instrument-risk'}

REQUIRED = ('slug', 'title', 'category', 'summary', 'takeaways',
            'sections', 'last_updated')


def fail(msg):
    print('FAIL  %s' % msg)
    sys.exit(1)


def main():
    with open(SRC, encoding='utf-8') as fh:
        guides = json.load(fh)

    with open(GLOSSARY, encoding='utf-8') as fh:
        known_terms = {g['slug'] for g in json.load(fh)}

    # Every page the guides are allowed to point at. Checked against the real
    # files rather than a list, so a renamed page is caught here.
    pages = {'/' + f for f in os.listdir(ROOT) if f.endswith('.html')}

    slugs = set()
    for g in guides:
        for key in REQUIRED:
            if key not in g:
                fail('guide %r is missing %r' % (g.get('slug', '?'), key))

        if g['slug'] in slugs:
            fail('duplicate slug %r' % g['slug'])
        slugs.add(g['slug'])

        if g['category'] not in CATEGORIES:
            fail('guide %r has unknown category %r (known: %s)'
                 % (g['slug'], g['category'], ', '.join(sorted(CATEGORIES))))

        if not g['takeaways']:
            fail('guide %r has no takeaways' % g['slug'])

        for s in g['sections']:
            if not s.get('title') or not s.get('paragraphs'):
                fail('guide %r has a section missing a title or body' % g['slug'])

        for term in g.get('related_terms', []):
            if term not in known_terms:
                fail('guide %r links to glossary slug %r, which does not exist'
                     % (g['slug'], term))

        for tool in g.get('related_tools', []):
            href = tool.get('href', '')
            if href not in pages:
                fail('guide %r links to %r, which is not a page in the repo'
                     % (g['slug'], href))

    body = json.dumps(guides, indent=2, ensure_ascii=False)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write('// GENERATED by scripts/build_guides_twin.py. Do not edit.\n')
        fh.write('// Source of truth is data/guides.json; edit that and re-run.\n')
        fh.write('window.GUIDES_DATA = %s;\n' % body)

    words = sum(len(p.split())
                for g in guides for s in g['sections'] for p in s['paragraphs'])
    print('OK    %d guides, %d sections, ~%d words'
          % (len(guides),
             sum(len(g['sections']) for g in guides),
             words))
    print('OK    every related_terms slug exists in the glossary')
    print('OK    every related_tools href is a real page')
    print('      wrote %s' % os.path.relpath(OUT, ROOT))


if __name__ == '__main__':
    main()
